# Generated by Django 3.0.4 on 2020-03-15 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20200315_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_by',
            field=models.ManyToManyField(default=None, null=True, related_name='user_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
